### ISSUE TITLE
Locale issue

### ISSUE THREAD

**Issue by GerryGilmore** [CreamyCRM/Creamy#3]
Hi. I followed the wiki and did install the php5-intl module (Linux Mint 17.2), but I am still getting the error on install.php on line 37

Could it be an apache setting as it's getting the HTTP_ACCEPT_LANGUAGE variable.... (I'm in the US) or something else?

Thanks!

Gerry

**Comment by DigitalLeaves** [comment]
Hi Gerry,
Could you please send me the output from the error log or the error message to better understand what's going on? It should work with any Apache locale setting.

Thanks in advance.
Ignacio.

**Comment by GerryGilmore** [comment]
Here you go, and thanks for the response!

Gerry

**Comment by DigitalLeaves** [comment]
Hi there,
I can't find the log or the error message anywhere, am I missing something?
Thanks!

**Comment by GerryGilmore** [comment]
Ignacio,

Sorry about that - I had attached the error.log file as an attachment,
which was apparently not picked up by github. Here is the message from the
apache log....

[Mon Sep 28 18:39:52.366015 2015] [mpm_event:notice] [pid 3235:tid
140563270625152] AH00489: Apache/2.4.7 (Ubuntu) configured -- resuming
normal operations
[Mon Sep 28 19:44:01.876130 2015] [mpm_prefork:notice] [pid 3061] AH00169:
caught SIGTERM, shutting down
[Mon Sep 28 19:44:33.933360 2015] [mpm_prefork:notice] [pid 3748] AH00163:
Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.12 configured -- resuming normal
operations
[Mon Sep 28 19:44:33.933678 2015] [core:notice] [pid 3748] AH00094: Command
line: '/usr/sbin/apache2'
[Mon Sep 28 19:46:29.996615 2015] [mpm_prefork:notice] [pid 3748] AH00169:
caught SIGTERM, shutting down
[Mon Sep 28 19:47:01.982286 2015] [mpm_prefork:notice] [pid 3908] AH00163:
Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.12 configured -- resuming normal
operations
[Mon Sep 28 19:47:01.982410 2015] [core:notice] [pid 3908] AH00094: Command
line: '/usr/sbin/apache2'
[Mon Sep 28 19:52:43.525053 2015] [mpm_prefork:notice] [pid 3908] AH00169:
caught SIGTERM, shutting down
[Mon Sep 28 19:52:44.886963 2015] [mpm_prefork:notice] [pid 4014] AH00163:
Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.12 configured -- resuming normal
operations
[Mon Sep 28 19:52:44.887206 2015] [core:notice] [pid 4014] AH00094: Command
line: '/usr/sbin/apache2'
[Mon Sep 28 19:53:24.119527 2015] [:error] [pid 4018] [client
127.0.0.1:53177] PHP Fatal error:  Class 'Locale' not found in
/var/www/html/Creamy-master/install.php on line 37
[Mon Sep 28 19:59:50.565419 2015] [mpm_prefork:notice] [pid 4014] AH00169:
caught SIGTERM, shutting down
[Mon Sep 28 20:01:03.716518 2015] [mpm_prefork:notice] [pid 2741] AH00163:
Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.12 configured -- resuming normal
operations
[Mon Sep 28 20:01:03.744108 2015] [core:notice] [pid 2741] AH00094: Command
line: '/usr/sbin/apache2'
[Mon Sep 28 20:01:20.010106 2015] [:error] [pid 2820] [client
127.0.0.1:52882] PHP Fatal error:  Class 'Locale' not found in
/var/www/html/Creamy-master/install.php on line 37
[Mon Sep 28 20:04:20.823295 2015] [:error] [pid 2822] [client
127.0.0.1:52885] PHP Fatal error:  Class 'Locale' not found in
/var/www/html/Creamy-master/install.php on line 37

Thanks again!

Gerry

**Comment by DigitalLeaves** [comment]
Well, that's strange because that's exactly the message you would get if you don't have the php-intl extension properly installed.

Can you please do a simple test? write a php page in your server (something like testphp.php) with the following content:
<?php
   phpinfo();
?>

And then visit the page and look for something similar to this:
<img width="987" alt="captura de pantalla 2015-09-29 a las 18 29 06" src="https://cloud.githubusercontent.com/assets/5340535/10171004/0be795b0-66d8-11e5-9d9b-0e45ac255c0b.png">

(don't forget to delete the file afterwards for security reasons ;).
Thank you.

**Comment by GerryGilmore** [comment]
That's definitely the issue. I did not find the intl section at all, though
Synaptic shows that the php5-intl package is installed..... I'll do a
reinstall as I obviously munged something up and I'll let you know the
results.

Thanks again for your help!

Gerry

**Comment by DigitalLeaves** [comment]
You are welcome, I usually employ Debian for my backends/servers, and it comes with the Intl module enabled by default in Apache, but in other distributions it might need to be enabled manually.

Please let me know how it finally goes, and of course if you find any other issue please let me know.
Best!

**Comment by GerryGilmore** [comment]
Will do! BTW, when you mention intl enabled in apache, did you mean enabled
in php?

Thanks,

Gerry

**Comment by DigitalLeaves** [comment]
Yes, sorry. Usually in Debian it implies having a file called intl.ini in /etc/php5/mods-available and the proper configuration in /etc/php5

**Comment by GerryGilmore** [comment]
Quick update...I reinstalled and verified that the intl package was enabled
and now it works great. However, upon completing the install after
assigning the admin name and password, I was prompted to start using Creamy
so I hit the Start button and it restarted the installation again.

In looking at the script, it appears to have not created the
CRM_INSTALLED_FILE (a text file in the local directory). I'm not good
enough at php to have determined what might have gone wrong, but I wanted
to see if it was safe to just touch that file to have it exist and launch
again. Normally, I would anyway, but I wanted to see if it was something
you'd want to look at before I bust around it. :-)

Thanks,

Gerry

**Comment by DigitalLeaves** [comment]
Hi Gerry,

Probably you are experiencing a problem with permissions. If your files have root:root permissions, www-data (our your apache user's name) was unable to write two important files during the installation process:
1. The installed.txt file that tells Creamy that there is a proper installation there.
2. The config file with the database details for Creamy to access your MySQL database data.

You can change the permissions (chown www-data:www-data creamy -R) and then you have two options:
a. re-install again (just delete the database tables created during installation).
b. try to re-create the installation files:
   b.1. create an empty installed.txt file at the creamy's root level.
   b.2. create a file in php/ called Config.php, with the following content:
```<?php
// specific instalation configuration

// database configuration
define('DB_USERNAME', 'your_ddbb_username');
define('DB_PASSWORD', 'your_ddbb_username_password');
define('DB_HOST', 'localhost');
define('DB_NAME', 'your_ddbb_database_name');
define('DB_PORT', '3306');

// other configuration parameters			
define('CRM_ADMIN_EMAIL', 'your@email.com');
?>
```

I should probably mention the thing with permission in files somewhere in the installation guide. Thanks for pointing it out to me. 
I really hope it helps!

**Comment by GerryGilmore** [comment]
Again, you were right. I had unzipped the file as root and even though I
redid it under a normal user, I still needed to chmod all of the
directories.

Thanks again,

Gerry
