### ISSUE TITLE
cannot install creamy in a docker environment

### ISSUE THREAD

**Issue by grexe** [CreamyCRM/Creamy#4]
As there is sadly no demo or docker image available, I tried to find out myself, sadly a frustrating experience.
First try with linuxconfig/lemp image from docker hub failed because of an outdated PHP install that had no internationalization extensions installed.
Second try with jacobom/lemp image got me as far as to the 2nd page of the creamy installation wizard, but after completing the data (even tried with the *root* dabatase user), it always jumps back to the first page, without giving any error message.

**Comment by DigitalLeaves** [comment]
Hi Gregor,

Sorry to hear about your issues, but surely apart from writing the software open source, so you can use if for free, you wouldn't want me to install it to you in your custom docker/whatever platform, now would you?

Please, try to install the software in a PHP/MySQL local server that fulfills the requisites (PHP version, Intl, etc) and then understand why it's not working in your docker environment. Best

**Comment by grexe** [comment]
Ignacio, of course I'd not expect that, but  my point was different:
I need a proper error message if something goes wrong, but the installation wizard just jumps back to the 1st page without giving any indication on what went wrong.
This has nothing to do with docker, because, as I said, that image works just fine, MySQL+nginx configured properly, I can access and use the database, but CreamyCRM fails for some unknown reason.

**Comment by DigitalLeaves** [comment]
Hi Gregor,

I’m afraid I cannot really help you without knowing what’s happening. If you could send me a dump of the error log (including PHP error messages) and probably the console output (because something could be going wrong at a JS level) maybe I could tell you more.

Best.

**Comment by grexe** [comment]
That's exactly my problem - I don't get any error on the client and couldn't yet find anything useful in the server logs, but I'll check again in the evening and tell you more...

**Comment by DigitalLeaves** [comment]
Thanks Gregor, please understand that I can’t really do anything without having a clue of what’s happening.

Maybe you can somehow replicate the docker instance’s configuration locally and try to guess?

Best.

**Comment by kwisatz** [comment]
Just for the record, I have also attempted running Creamy in a docker container. The first issue I encountered was a missing php5-intl package, but that's explained in the installation guide, so not really Creamy's fault but mine.

Though, once I had successfully completed the installation wizard and it prompted me to log in, the index.php file still redirects me to install.php.

I discovered that installed.txt had not been created, nor had the configuration data been written to file. The problem here is that the installer does not complain when it can't write those files.

**Comment by kwisatz** [comment]
Or maybe not… Discovered a lot of other issues which leaves me in doubt if we really have the time to invest here. The latest commits are 8 months old, is this project still alive or not?

**Comment by DigitalLeaves** [comment]
Hi, the project is still alive, unfortunately I don't have that much time to work on it lately, I have bills to pay you know. I have it installed for my company and many of my customers and users all around the world are using it happily without problems. 

It's open software, so it may be not as polished as a commercial product. If you don't know how to admin a server and properly manage php modules and permissions on your files, or don't have time to invest in this, maybe you would need to use a commercial product.

If you think Creamy can be improved, then we agree on that, and I would be glad to have you onboard to help me improve it. If not, don't waste your time and pay for quality software.

Best.
