### ISSUE TITLE
No mysql socket support on install

### ISSUE THREAD

**Issue by laurentelgard** [CreamyCRM/Creamy#5]
Hi,
Thanks for your work !
Actually i get frustrated as i can not install creamy on my 1&1 server ; mysql needs a connexion via socket, to localhost:/tmp/mysql5.sock for instance, and there's a lot of source code to inspect.
Any quick idea on how to modify the database handler to support socket too ?
Thanks a lot,
Laurent

**Comment by laurentelgard** [comment]
Ok got it, got to modify function connect() in db connectors: great!

**Comment by DigitalLeaves** [comment]
Hi Lauren, nice to know you figured it out, creamy actually uses MysqlND, and sockets should be easy to add. please don't hesitate to share your code and I can integrate it for people in your same situation. Thanks.

**Comment by laurentelgard** [comment]
Hum well i've juste modified line 169 of php/db_connectors/MysqliDb.php by adding the socket at the end of the parameters, would be great to modify the install view et logic btw.

*For 1&1 managed servers:*
<pre>
@$this->_mysqli = new mysqli ($this->host, $this->username, $this->password, $this->db, $this->port,'/tmp/mysql5.sock');
</pre>

**Comment by DigitalLeaves** [comment]
Thanks Lauren, I will think on a way of doing this more generic from your situation at 1&1. Best regards!
